# Generated by Django 4.2.9 on 2024-01-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(
                choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin')],
                default='MEMBER',
                help_text='회원 등급',
                max_length=10,
            ),
        ),
    ]
