# Generated by Django 4.2.9 on 2024-01-04 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Snack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Snack name.", max_length=128
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, help_text="A url for buy the snack.", max_length=500
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                (
                    "currency",
                    models.CharField(
                        choices=[("KRW", "Krw"), ("USD", "Usd"), ("JPY", "Jpy")],
                        default="KRW",
                        max_length=4,
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        db_index=True,
                        editable=False,
                        length=22,
                        max_length=22,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "snacks_cart",
                    models.ManyToManyField(through="order.Cart", to="order.snack"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cart",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.order"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="snack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="order.snack"
            ),
        ),
    ]
