# Generated by Django 4.2.9 on 2024-01-04 08:36

from django.db import migrations, models
import snack.order.models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='desc',
            field=models.TextField(blank=True, help_text='Snack description'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to=snack.order.models.snack_image_path),
        ),
    ]
