# Generated by Django 4.2.9 on 2024-01-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0002_snack_desc_alter_snack_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(blank=True, help_text='Snack name.', max_length=128, unique=True),
        ),
    ]
