# Generated by Django 4.2.9 on 2024-01-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0004_rename_snacks_cart_order_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('CREATED', 'Created'),
                    ('ORDERED', 'Ordered'),
                    ('CANCELLED', 'Cancelled'),
                    ('APPROVED', 'Approved'),
                    ('SHIPPING', 'Shipping'),
                    ('COMPLETED', 'Completed'),
                ],
                default='CREATED',
                max_length=20,
            ),
        ),
    ]
