# Generated by Django 4.2.9 on 2024-01-10 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.snack', to_field='name'),
        ),
        migrations.CreateModel(
            name='SnackReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'Like'), ('HATE', 'Hate')], default='LIKE', max_length=10)),
                (
                    'snack',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='snack_reactions',
                        to='order.snack',
                        to_field='name',
                    ),
                ),
            ],
        ),
    ]
