# Generated by Django 4.2.9 on 2024-01-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0006_alter_cart_snack_snackreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackreaction',
            name='snack',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='snack_reactions',
                to='order.snack',
                to_field='uid',
            ),
        ),
    ]
