# Generated by Django 4.2.9 on 2024-01-15 05:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0008_rename_cart_purchase_remove_order_carts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchases',
            new_name='snacks',
        ),
    ]
