# Generated by Django 4.2.9 on 2024-01-16 03:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0009_rename_purchases_order_snacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='snacks',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='purchases',
            field=models.ManyToManyField(related_name='snacks', through='order.Purchase', to='order.snack'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='snackreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snackreaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, editable=False, length=22, max_length=22, prefix='', unique=True
            ),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.snack'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, editable=False, length=22, max_length=22, prefix='', unique=True
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uid'], name='order_order_uid_b7a83a_idx'),
        ),
        migrations.AddIndex(
            model_name='snack',
            index=models.Index(fields=['uid'], name='order_snack_uid_9e8276_idx'),
        ),
    ]
