# Generated by Django 4.2.9 on 2024-01-15 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0009_rename_purchases_order_snacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='snack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.snack'),
        ),
    ]
