# Generated by Django 4.2.9 on 2024-01-17 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0010_remove_order_snacks_order_created_at_order_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackreaction',
            name='user',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
