# Generated by Django 4.2.9 on 2024-01-15 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0010_alter_purchase_snack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='snacks',
            new_name='purchases',
        ),
    ]
