# Generated by Django 4.2.9 on 2024-01-15 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0011_rename_snacks_order_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchases',
            new_name='snacks',
        ),
    ]
