# Generated by Django 4.2.9 on 2024-01-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0011_snackreaction_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='snackreaction',
            index=models.Index(fields=['snack'], name='order_snack_snack_i_5e5b92_idx'),
        ),
    ]
