# Generated by Django 4.2.9 on 2024-01-18 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_snackreaction_order_snack_snack_i_5e5b92_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackreaction',
            name='snack',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='snack_reactions', to='order.snack'
            ),
        ),
    ]
