# Generated by Django 4.2.9 on 2024-01-15 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0012_rename_purchases_order_snacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='snacks',
            new_name='purchases',
        ),
    ]
