# Generated by Django 4.2.9 on 2024-01-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0013_alter_snackreaction_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
