# Generated by Django 4.2.9 on 2024-01-16 01:19

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0013_rename_snacks_order_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchases',
            field=models.ManyToManyField(related_name='snacks', through='order.Purchase', to='order.snack'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, editable=False, length=22, max_length=22, prefix='', unique=True
            ),
        ),
        migrations.AlterField(
            model_name='snack',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, editable=False, length=22, max_length=22, prefix='', unique=True
            ),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['uid'], name='order_order_uid_b7a83a_idx'),
        ),
        migrations.AddIndex(
            model_name='snack',
            index=models.Index(fields=['uid'], name='order_snack_uid_9e8276_idx'),
        ),
    ]
