# Generated by Django 4.2.9 on 2024-01-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0014_snack_estimated_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='estimated_arrival_time',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
