# Generated by Django 4.2.9 on 2024-01-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0015_remove_snack_estimated_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='hate_reaction_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snack',
            name='like_reaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
