# Generated by Django 4.2.9 on 2024-01-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0016_snack_hate_reaction_count_snack_like_reaction_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='like_ratio',
            field=models.FloatField(default=0, help_text='싫어요 대비 좋아요 비율. hate / like.'),
        ),
    ]
