# Generated by Django 4.2.9 on 2024-01-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('order', '0017_snack_like_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='hate_reaction_count',
            field=models.IntegerField(default=0, help_text='hate reaction 합산'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='like_reaction_count',
            field=models.IntegerField(default=0, help_text='like reaction 합산'),
        ),
    ]
