# Generated by Django 4.2.9 on 2024-02-01 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import snack.order.model_mixins


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0019_order_day_order_month_order_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'uid',
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, editable=False, length=22, max_length=22, prefix='', unique=True
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('CREATED', 'Created'),
                            ('ORDERED', 'Ordered'),
                            ('CANCELLED', 'Cancelled'),
                            ('APPROVED', 'Approved'),
                            ('SHIPPING', 'Shipping'),
                            ('COMPLETED', 'Completed'),
                        ],
                        default='CREATED',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(snack.order.model_mixins.OrderMixin, models.Model),
        ),
    ]
